# Generated by Django 3.1.2 on 2020-10-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_imagr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagr',
            field=models.ImageField(null=True, upload_to='posts/'),
        ),
    ]
