# Generated by Django 3.1.2 on 2020-10-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201021_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='author',
            new_name='phon',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
